images:
  airflow:
    repository: local/airflow
    tag: "dev"

env:
  - name: AWS_DEFAULT_REGION
    value: ${aws_region}
  - name: AWS_ENDPOINT_URL
    value: "${localstack_endpoint_url}"
  - name: RAW_SATELLITE_BUCKET
    value: ${raw_satellite_bucket}
  - name: PROCESSED_AOI_BUCKET
    value: ${processed_aoi_bucket}
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "true"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "s3://${airflow_logs_bucket}"
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: "aws_default"
  - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
    value: "false"
  - name: AIRFLOW_CONN_AWS_DEFAULT
    value: |
      {
        "conn_type": "aws",
        "login": "${aws_access_key}",
        "password": "${aws_secret_key}",
        "extra": {
          "region_name": "${aws_region}",
          "endpoint_url": "http://localstack.${data_lab_namespace}.svc.cluster.local:4566"
        }
      }

secret:
  - envName: AWS_ACCESS_KEY_ID
    secretName: ${aws_credentials_secret_name}
    secretKey: AWS_ACCESS_KEY_ID
  - envName: AWS_SECRET_ACCESS_KEY
    secretName: ${aws_credentials_secret_name}
    secretKey: AWS_SECRET_ACCESS_KEY

executor: KubernetesExecutor

airflow:
  migrationsWaitTimeout: 600
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 30

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "latest"
  auth:
    username: airflow
    password: airflow
    database: airflow


webserver:
  enabled: true
  defaultUser:
    enabled: true
    username: admin
    password: admin
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "0.2"
      memory: "256Mi"

scheduler:
  resources:
    requests:
      cpu: "0.2"
      memory: "256Mi"

worker:
  resources:
    requests:
      cpu: "0.2"
      memory: "256Mi"

triggerer:
  resources:
    requests:
      cpu: "0.2"
      memory: "256Mi"

dags:
  persistence:
    enabled: true
    size: 512Mi

# To avoid immutable Job manifest issues and to keep updates stable when deploying using Terraform
# https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
