version: 2

models:
  - name: stg_raw_ndvi_observations
    columns:
      - name: aoi_id
        tests:
          - not_null
      - name: observed_on
        tests:
          - not_null
      - name: status
        tests:
          - not_null
  - name: fct_aoi_daily_ndvi
    columns:
      - name: aoi_id
        tests:
          - not_null
      - name: observed_on
        tests:
          - not_null
      - name: status
        tests:
          - not_null
